version: "3.8"

services:
  node:
    build: .
    container_name: nodejs
    command: sh -c "npm install -g nodemon && nodemon *.js"
    command: tail -f /dev/null
    networks:
      - test

  jenkins:
    build: ./jenkins/
    container_name: jenkins
    privileged: true
    pull_policy: never
    env_file: .env
    environment:
      - JENKINS_ADMIN_ID:$JENKINS_ADMIN_ID
      - JENKINS_ADMIN_PASSWORD:JENKINS_ADMIN_PASSWORD
    ports:
      - 8085:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - test

networks:
  test:

volumes:
  jenkins_home:
