FROM jenkins/jenkins:lts-jdk11

USER root

RUN apt-get update && apt-get install -y nodejs

ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false

ENV CASC_JENKINS_CONFIG /var/jenkins_home/casc.yaml

COPY plugins.txt /usr/share/jenkins/ref/plugins.txt

RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt

COPY casc.yaml /var/jenkins_home/casc.yaml

COPY job/config.xml.override /usr/share/jenkins/ref/jobs/webdriverio-test/config.xml.override
